---
name: CI CD

on: [push]
env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 2.6.5

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
      - name: Deploy
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG
          ./.github/deploy.rb